server {
    #FICA A ESCUTA EXCLUSIVAMENTE NA PORTA 443 COM CIFRA SSL/TLS (IPV4 E IPV6)
    listen 443 ssl;
    listen [::]:443 ssl;


    server_name dviegas.42.fr;

    #LOCALIZACAO DAS CHAVES GERADAS PELO OpenSSL
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Restrição estrita aos protocolos exigidos
    ssl_protocols TLSv1.2 TLSv1.3;

    #RAIZ ONDE FICARAO OS FICHEIROS DO WORDPRESS MONTADOS VIA VOLUME
    root /var/www/html;
    index index.php index.html index.htm;

    #GESTAO DE URLS AMIGAVEIS
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # Encaminhamento FastCGI para o WordPress (php-fpm)
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}



#IMPEDE CONEXOES INSEGURAS (PORTA 80 DESLIGADA), RESTRINGE CIFRAS FRACAS
#ENTREGA O TRAFEGO .PHP PARA O CONTENTOR WORDPRESS NA PORTA INTERNA 9000.
